### ISSUE TITLE
BUG: FTL failed to ask question: json: cannot unmarshal string into Go value of type []interface {}

### ISSUE THREAD

**Issue by Haiz14** [mosajjal/bard-cli#7] opened 2023-06-08 14:53 UTC
Reproduce
- install latest version of `bard-cli`
```bash
go install github.com/mosajjal/bard-cli@latest
go: downloading github.com/mosajjal/bard-cli v0.3.2
```

Asks a question 
```bash

❯ bard-cli "github clone only latest commit"
2023-06-08T14:50:56Z FTL failed to ask question: json: cannot unmarshal string into Go value of type []interface {}
```

**Comment by mosajjal** [comment] 2023-06-08 20:48
yep can confirm this is an issue as of a few hours ago. have you checked other implementations of Bard CLI to see if the issue is present there as well?

**Comment by Haiz14** [comment] 2023-06-09 02:28
Yeah this is an issue on databingo/aih too, bard isn't working there 

My guess is that the json return format has been tweaked by google. Cause a request is sent, processed but nothing is being printed.

**Comment by mosajjal** [comment] 2023-06-09 05:43
should be fixed in https://github.com/mosajjal/bard-cli/releases/tag/v0.3.3

**Closed as completed by mosajjal** 2023-06-09 05:43 UTC
